In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
a2 = np.array([[1,2,3],
               [3,4,5]])
print(a2)
a2.shape

[[1 2 3]
 [3 4 5]]


(2, 3)

In [6]:
a3 = np.array([[[1,2,3],
                [1,2,3],
                [1,2,3]],
               [[1,2,3],
                [1,2,3],
                [1,2,3]]])
a3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [7]:
import pandas as pd

In [10]:
d1 = pd.DataFrame(a2,index=['row1','row2'],columns=['column1','column2','column3'])
d1

column1  column2  column3
row1        1        2        3
row2        3        4        5

In [11]:
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
zereos = np.zeros((7,3,2))
zereos

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
a4 = np.arange(0,100,3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
a5 = np.random.randint(0,10,size=(7,2))
a5

array([[0, 9],
       [1, 4],
       [3, 2],
       [3, 4],
       [6, 5],
       [5, 5],
       [7, 5]])

In [17]:
a6 = np.random.random((3,2))
a6

array([[0.50962849, 0.18765343],
       [0.74271634, 0.16400252],
       [0.60890678, 0.35223733]])

In [20]:
np.random.seed(42)
a7 = np.random.randint(0,10,size=(4,6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [21]:
np.unique(a7)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [22]:
a7[0]

array([6, 3, 7, 4, 6, 9])

In [23]:
a7[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [29]:
a7[:2,:2]

array([[6, 3],
       [2, 6]])

In [31]:
a8 = np.ones((4,6))
a8

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
a7+a8

array([[ 7.,  4.,  8.,  5.,  7., 10.],
       [ 3.,  7.,  8.,  5.,  4.,  8.],
       [ 8.,  3.,  6.,  5.,  2.,  8.],
       [ 6.,  2.,  5.,  1., 10.,  6.]])

In [34]:
a9 = np.random.randint(0,10,size=(3,3))
a9

array([[8, 0, 9],
       [2, 6, 3],
       [8, 2, 4]])

In [35]:
a10 = np.random.randint(0,10,size=(3,2))
a10

array([[2, 6],
       [4, 8],
       [6, 1]])

In [36]:
np.dot(a9,a10)

array([[70, 57],
       [46, 63],
       [48, 68]])

In [37]:
a11 = np.random.randint(0,10,size=(4,3))
a11

array([[3, 8, 1],
       [9, 8, 9],
       [4, 1, 3],
       [6, 7, 2]])

In [39]:
a12 = np.random.randint(0,10,size=(4,3))
a12

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4],
       [1, 4, 7]])

In [40]:
a11>a12

array([[False,  True, False],
       [ True,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [41]:
a11>7

array([[False,  True, False],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [42]:
np.sort(a11)

array([[1, 3, 8],
       [8, 9, 9],
       [1, 3, 4],
       [2, 6, 7]])

In [43]:
np.argsort(a11)

array([[2, 0, 1],
       [1, 0, 2],
       [1, 2, 0],
       [2, 0, 1]], dtype=int32)

In [45]:
a12 = np.arange(1,100,10)
a12

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])